[tool.poetry]
name = "hympi-ml"
package-mode = false

[tool.poetry.dependencies]
python = "~3.10"
mlflow = "^2.15.1"
numpy = "^1.9"
matplotlib = "^3.9.2"
tensorflow = {version = "~2.11", extras = ["and-cuda"]}
notebook = "^7.2.2"
pydantic = "^2.8.2"
mypy = "^1.11.2"
rich = "^13.8.0"
ipywidgets = "^8.1.5"
optuna = "^4.0.0"
h5netcdf = "^1.3.0"
pandas = "^2.2.3"
geopandas = "^1.0.1"

[tool.poetry.group.dev.dependencies]
ruff = "^0.6.8"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    # "I",  # isort
    "B",  # flake8-bugbear
    "C4",  # flake8-comprehensions
    "N",  # PEP8 naming convetions
    # "D"  # pydocstyle
]
ignore = [
    "C901",  # too complex
    "W191",  # indentation contains tabs
    "D401"  # imperative mood
]

[tool.ruff.lint.pydocstyle]
convention = "google"