[tool.poetry]
name = "hympi-ml"
package-mode = false

[tool.poetry.dependencies]
python = "~3.10"
mlflow = "^2.15.1"
numpy = "^1.9"
matplotlib = "^3.9.2"
tensorflow = {version = "~2.11", extras = ["and-cuda"]}
notebook = "^7.2.2"
pydantic = "^2.8.2"
mypy = "^1.11.2"
rich = "^13.8.0"
ipywidgets = "^8.1.5"
optuna = "^4.0.0"
h5netcdf = "^1.3.0"
