[tool.poetry]
name = "hympi-ml"
package-mode = false

[tool.poetry.dependencies]
python = "3.10.5"
mlflow = "^2.15.1"
numpy = "^1.9"
matplotlib = "^3.9.2"
notebook = "^7.2.2"
tensorflow = "~2.10.0"
tensorflow-gpu = "~2.10.0"
hydra-core = "^1.3.2"
pydantic = "^2.8.2"
mypy = "^1.11.2"
rich = "^13.8.0"
ipywidgets = "^8.1.5"
netcdf4 = "^1.7.1.post2"
