# Set to true to prevent data being loaded
dry_run: False
verbose: True

# ensure that all config files have this "config" option with a target of conf.config.Config
config:
  _target_: conf.config.Config

  mlflow_experiment_name: Water Vapor Trop
  dataset_name: HSEL+BSL

  modelIOs:
    _target_: preprocessing.DataPreprocessor.create_modelIOs

    verbose: ${verbose}

    feature_processors:
      - _target_: preprocessing.DataPreprocessor.DataPreprocessor
        dataName: HyMPI_Composite
        transformer:
          _target_: sklearn.preprocessing.RobustScaler
        splitter: ${splitter}

      - _target_: preprocessing.DataPreprocessor.DataPreprocessor
        dataName: Surface_Pressure
        transformer:
          _target_: sklearn.preprocessing.RobustScaler
        splitter: ${splitter}

      - _target_: preprocessing.DataPreprocessor.DataPreprocessor
        dataName: BSL
        transformer:
          _target_: sklearn.preprocessing.RobustScaler
        splitter: ${splitter}

    target_processor:
      _target_: preprocessing.DataPreprocessor.DataPreprocessor
      dataName: Water_Vapor
      transformer:
        _target_: sklearn.preprocessing.RobustScaler
      splitter: ${splitter}

  model:
    # testing module is custom_ml
    _target_: model_creation.custom_mlp.build_multipath_mlp_model
    path_mlp_datas:
      - _target_: model_creation.mlp.MLPData
        layer_sizes: [1957, 128, 128, 64, 64]
        activation: gelu
        dropout_rate: 0.2

      - _target_: model_creation.mlp.MLPData
        layer_sizes: [1]
        activation: gelu
        dropout_rate: 0.2

      - _target_: model_creation.mlp.MLPData
        layer_sizes: [733, 128, 128, 64, 32]
        activation: gelu
        dropout_rate: 0.2

    output_mlp_data:
      _target_: model_creation.mlp.MLPData
      layer_sizes: [128, 64, 64, 72]
      activation: gelu
      output_activation: linear
      dropout_rate: 0.2

  compile_args:
    optimizer:
      _target_: tensorflow.keras.optimizers.Adam
    loss:
      _target_: tensorflow.keras.losses.MeanAbsoluteError

  fit_args:
    batch_size: 6384
    epochs: 1000
    validation_split: 0.1
    verbose: 1
    callbacks:
      - _target_: keras.callbacks.EarlyStopping
        monitor: val_loss
        patience: 100
        verbose: ${verbose}

  evaluator:
    _target_: evaluation.ProfileEvaluator.ProfileEvaluator
    show_plot: False
    net_cdf: /data/nature_run/nc

splitter:
  _target_: preprocessing.splitters.FileSplitter
  data_loader:
    _target_: preprocessing.DataLoader.DataLoader
    file_path: /data/nature_run/work/data/bt_bslcpl532_all_72sigma_trop.npz
    dry_run: ${dry_run}
  indices_path: /data/nature_run/work/train_test_split_trop.pkl

#dry_run: True
